<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Spec\CitationScanner;
use App\Spec\Requirement;
use App\Spec\RequirementCatalogue;
use App\Spec\RequirementStatus;
use App\Spec\SpecFiles;
use App\Spec\StatusLedger;
use Illuminate\Console\Command;

/**
 * The traceability gate.
 *
 * Answers two questions no test runner can: is every requirement accounted
 * for, and does everything we claim is done actually have a test proving it.
 */
final class SpecCoverageCommand extends Command
{
    protected $signature = 'spec:coverage {--no-write : Report only, do not rewrite docs/spec/COVERAGE.md}';

    protected $description = 'Cross-reference the requirements, the status ledger and the tests that cite them';

    public function handle(): int
    {
        $catalogue = RequirementCatalogue::default();
        $ledger = StatusLedger::default();
        $citations = CitationScanner::default()->citations();

        $violations = [];

        foreach ($catalogue->all() as $requirement) {
            $status = $ledger->statusFor($requirement->id);

            if ($status === null) {
                $violations[] = "{$requirement->id} is missing from docs/spec/status.txt — run `php artisan spec:index`.";

                continue;
            }

            if ($status->requiresTest() && ! isset($citations[$requirement->id])) {
                $violations[] = "{$requirement->id} is marked `done` but no test cites it.";
            }

            if ($status->requiresReason() && $ledger->reasonFor($requirement->id) === '') {
                $violations[] = "{$requirement->id} is marked `{$status->value}` without a reason.";
            }
        }

        foreach (array_keys($citations) as $citedId) {
            if (! $catalogue->has($citedId)) {
                $violations[] = sprintf(
                    '%s is cited by %s but docs/REQUIREMENTS.md does not declare it.',
                    $citedId,
                    implode(', ', $citations[$citedId]),
                );
            }
        }

        $this->report($catalogue, $ledger, $citations);

        if (! $this->option('no-write')) {
            $this->writeReport($catalogue, $ledger, $citations);
        }

        if ($violations !== []) {
            $this->newLine();

            foreach ($violations as $violation) {
                $this->components->error($violation);
            }

            return self::FAILURE;
        }

        return self::SUCCESS;
    }

    /**
     * @param  array<string, list<string>>  $citations
     */
    private function report(RequirementCatalogue $catalogue, StatusLedger $ledger, array $citations): void
    {
        $zeroed = array_fill_keys(
            array_map(fn (RequirementStatus $status) => $status->value, RequirementStatus::cases()),
            0,
        );

        $rows = [];
        $totals = $zeroed;

        foreach ($catalogue->byArea() as $prefix => $requirements) {
            $counts = $zeroed;

            foreach ($requirements as $requirement) {
                $status = $ledger->statusFor($requirement->id) ?? RequirementStatus::Planned;
                $counts[$status->value]++;
                $totals[$status->value]++;
            }

            $settled = $counts['done'] + $counts['changed'] + $counts['wont-do'];

            $rows[] = [
                $prefix,
                $catalogue->areaNames()[$prefix] ?? '',
                count($requirements),
                $counts['done'] ?: '–',
                $counts['in-progress'] ?: '–',
                $counts['changed'] ?: '–',
                $counts['wont-do'] ?: '–',
                sprintf('%d%%', (int) round($settled / max(count($requirements), 1) * 100)),
            ];
        }

        $this->table(
            ['', 'Area', 'Total', 'Done', 'WIP', 'Chg', 'Skip', 'Settled'],
            $rows,
        );

        $this->components->info(sprintf(
            '%d requirements · %d done · %d in progress · %d changed · %d won\'t do · %d cited by a test',
            count($catalogue->all()),
            $totals['done'],
            $totals['in-progress'],
            $totals['changed'],
            $totals['wont-do'],
            count(array_intersect(array_keys($citations), $catalogue->ids())),
        ));
    }

    /**
     * @param  array<string, list<string>>  $citations
     */
    private function writeReport(RequirementCatalogue $catalogue, StatusLedger $ledger, array $citations): void
    {
        $lines = [
            '# Requirement coverage',
            '',
            '<!-- Generated by `php artisan spec:coverage`. Do not edit by hand — edit',
            '     docs/spec/status.txt, or add a test citing the requirement id. -->',
            '',
            sprintf('Generated %s from `docs/REQUIREMENTS.md`.', now()->format('Y-m-d')),
            '',
            '| Requirement | Status | Cited by | Summary |',
            '| --- | --- | --- | --- |',
        ];

        foreach ($catalogue->all() as $requirement) {
            $status = $ledger->statusFor($requirement->id) ?? RequirementStatus::Planned;
            $reason = $ledger->reasonFor($requirement->id);
            $lines[] = sprintf(
                '| `%s` | %s%s | %s | %s |',
                $requirement->id,
                $status->value,
                $reason === '' ? '' : ' — '.$reason,
                $this->citedBy($citations, $requirement),
                str_replace('|', '\\|', $requirement->summary()),
            );
        }

        file_put_contents(SpecFiles::coverageReport(), implode("\n", $lines)."\n");

        $this->components->info('Wrote docs/spec/COVERAGE.md');
    }

    /** @param array<string, list<string>> $citations */
    private function citedBy(array $citations, Requirement $requirement): string
    {
        $files = $citations[$requirement->id] ?? [];

        return $files === [] ? '–' : implode('<br>', array_map(
            fn (string $file) => '`'.$file.'`',
            $files,
        ));
    }
}
